use home;

update wx_bill set tran_order = replace(trim(tran_order),'	','');


delete from home.rep_column where  sheet_id = 1;
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(1, 1, 1, 1, 10, '所属期间', 'string', 'accPeriod', 1, 1, 18, 70, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(2, 1, 1, 1, 20, '分类科目', 'string', 'subTypeName', 1, 1, 18, 70, '1', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(3, 1, 1, 1, 30, '科目代码', 'string', 'subCode', 1, 1, 18, 150, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(4, 1, 1, 1, 40, '科目名称', 'string', 'subName', 1, 1, 18, 150, '1', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(5, 1, 1, 1, 50, '金额', 'number', 'amount', 1, 1, 18, 100, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(6, 1, 1, 1, 60, '业务发生日期', 'string', 'accDate', 1, 1, 18, 100, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(7, 1, 1, 1, 70, '摘要', 'string', 'digest', 1, 1, 18, 100, '1', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(8, 1, 1, 1, 80, '结算方式', 'string', 'paymentTypeName', 1, 1, 18, 100, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(9, 1, 1, 1, 90, '创建时间', 'string', 'createDate', 1, 1, 18, 150, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(10, 1, 1, 1, 100, '创建人', 'string', 'createUserName', 1, 1, 18, 80, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(68, 1, 1, 1, 83, '交易商户', 'string', 'merchant', 1, 1, 18, 100, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);
INSERT INTO home.rep_column (col_id, rep_id, sheet_id, header_index, col_index, col_name, col_data_type, col_prop, row_span, col_span, height, width, is_necessary, create_date, create_user, update_date, update_user, is_data_merge_cell, is_number_format, is_metadata, metadata_router, metadata_self_params) VALUES(69, 1, 1, 1, 86, '商品', 'string', 'goods', 1, 1, 18, 100, '0', NULL, NULL, NULL, NULL, '0', '1', '0', NULL, NULL);